name: Update progs.json

# Run at 5am UTC every day
on:
  schedule:
  - cron: "0 5 * * *"

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run script
      run: go run ./src/nhk_expire_web.go -file="./src/progs.json"

    - name: Commit new progs
      run: |
        git config --global user.name 'metalfoxdev'
        git config --global user.email 'metalfoxdev@users.noreply.github.com'
        git commit -am "(AUTO) Update progs.json"
        git push

      
