name: Update programme list

# Run at 5am UTC every day
on:
  schedule:
  - cron: "0 5 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run script
      working-directory: ${{ github.workspace }}
      run: go run ./src/nhk_expire_web.go -file="src/progs.json"

    - name: Commit new progs
      working-directory: ${{ github.workspace }}
      run: |
        git fetch
        git config --global user.name 'metalfoxdev'
        git config --global user.email 'metalfoxdev@users.noreply.github.com'
        git commit -m "(DAILY) Update progs.json" src/progs.json
        git push

      
